package model;
// Generated 25-may-2018 8:47:00 by Hibernate Tools 4.3.1



/**
 * BillingData generated by hbm2java
 */
public class BillingData  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String dni;
     private String country;
     private String city;
     private String province;
     private String town;
     private String cp;
     private String adress;
     private String number;
     private String stairs;
     private String floor;
     private String door;

    public BillingData() {
    }

    public BillingData(User user, String dni, String country, String city, String province, String town, String cp,String adress, String number, String stairs, String floor, String door) {
       this.user = user;
       this.dni = dni;
       this.country = country;
       this.city = city;
       this.province = province;
       this.town = town;
       this.cp = cp;
       this.adress=adress;
       this.number = number;
       this.stairs = stairs;
       this.floor = floor;
       this.door = door;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public String getTown() {
        return this.town;
    }
    
    public void setTown(String town) {
        this.town = town;
    }
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }
    public String getAdress() {
        return this.adress;
    }
    
    public void setAdress(String adress) {
        this.adress= adress;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public String getStairs() {
        return this.stairs;
    }
    
    public void setStairs(String stairs) {
        this.stairs = stairs;
    }
    public String getFloor() {
        return this.floor;
    }
    
    public void setFloor(String floor) {
        this.floor = floor;
    }
    public String getDoor() {
        return this.door;
    }
    
    public void setDoor(String door) {
        this.door = door;
    }

    
    
    



}


