package model;
// Generated 25-may-2018 8:47:00 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private int id;
     private Budget budget;
     private Date date;
     private Date time;

    public Order() {
    }

    public Order(int id, Budget budget, Date date, Date time) {
       this.id = id;
       this.budget = budget;
       this.date = date;
       this.time = time;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Budget getBudget() {
        return this.budget;
    }
    
    public void setBudget(Budget budget) {
        this.budget = budget;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


