package model;
// Generated 25-may-2018 8:47:00 by Hibernate Tools 4.3.1



/**
 * Photos generated by hbm2java
 */
public class Photos  implements java.io.Serializable {


     private Integer id;
     private Request request;
     private byte[] photo;

    public Photos() {
    }

    public Photos(Request request, byte[] photo) {
       this.request = request;
       this.photo = photo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Request getRequest() {
        return this.request;
    }
    
    public void setRequest(Request request) {
        this.request = request;
    }
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }




}


