package model;
// Generated 25-may-2018 8:47:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Request generated by hbm2java
 */
public class Request  implements java.io.Serializable {


     private Integer id;
     private User userByIdClient;
     private User userByIdEmployee;
     private Date date;
     private Date time;
     private String state;
     private Set photoses = new HashSet(0);
     private Set budgets = new HashSet(0);

    public Request() {
    }

	
    public Request(User userByIdClient, User userByIdEmployee, Date date, Date time, String state) {
        this.userByIdClient = userByIdClient;
        this.userByIdEmployee = userByIdEmployee;
        this.date = date;
        this.time = time;
        this.state = state;
    }
    public Request(User userByIdClient, User userByIdEmployee, Date date, Date time, String state, Set photoses, Set budgets) {
       this.userByIdClient = userByIdClient;
       this.userByIdEmployee = userByIdEmployee;
       this.date = date;
       this.time = time;
       this.state = state;
       this.photoses = photoses;
       this.budgets = budgets;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUserByIdClient() {
        return this.userByIdClient;
    }
    
    public void setUserByIdClient(User userByIdClient) {
        this.userByIdClient = userByIdClient;
    }
    public User getUserByIdEmployee() {
        return this.userByIdEmployee;
    }
    
    public void setUserByIdEmployee(User userByIdEmployee) {
        this.userByIdEmployee = userByIdEmployee;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public Set getPhotoses() {
        return this.photoses;
    }
    
    public void setPhotoses(Set photoses) {
        this.photoses = photoses;
    }
    public Set getBudgets() {
        return this.budgets;
    }
    
    public void setBudgets(Set budgets) {
        this.budgets = budgets;
    }




}


