package model;
// Generated 25-may-2018 8:47:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String surname;
     private String email;
     private String phone;
     private String password;
     private String rol;
     private boolean active;
     private Set billingDatas = new HashSet(0);
     private Set requestsForIdClient = new HashSet(0);
     private Set requestsForIdEmployee = new HashSet(0);

    public User() {
    }

	
    public User(String name, String surname, String email, String phone, String password) {
        this.name = name;
        this.surname = surname;
        this.email = email;
        this.phone = phone;
        this.password = password;
        this.rol = "client";
        this.active = true;
    }
    public User(String name, String surname, String email, String phone, String password, String rol, boolean active, Set billingDatas, Set requestsForIdClient, Set requestsForIdEmployee) {
       this.name = name;
       this.surname = surname;
       this.email = email;
       this.phone = phone;
       this.password = password;
       this.rol = rol;
       this.active = active;
       this.billingDatas = billingDatas;
       this.requestsForIdClient = requestsForIdClient;
       this.requestsForIdEmployee = requestsForIdEmployee;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Set getBillingDatas() {
        return this.billingDatas;
    }
    
    public void setBillingDatas(Set billingDatas) {
        this.billingDatas = billingDatas;
    }
    public Set getRequestsForIdClient() {
        return this.requestsForIdClient;
    }
    
    public void setRequestsForIdClient(Set requestsForIdClient) {
        this.requestsForIdClient = requestsForIdClient;
    }
    public Set getRequestsForIdEmployee() {
        return this.requestsForIdEmployee;
    }
    
    public void setRequestsForIdEmployee(Set requestsForIdEmployee) {
        this.requestsForIdEmployee = requestsForIdEmployee;
    }

    

    


}


